# Generated by Django 4.0 on 2021-12-18 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_collection_featured_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descriptions',
            new_name='description',
        ),
    ]
